### PR TITLE
First implementation

### PR DESCRIPTION
**Pull request by blacktrub**
I want to make first step for our great future

### CODE REVIEW

**Review by xpsy — COMMENTED** [review]
It's not good, u need add `>>`

**Comment by blacktrub** [comment]
> It's not good, u need add `>>`

Thanks! Fixed

**Comment by dronov** [comment]
:+1:

**Comment by dronov** [comment]
@blacktrub have a nice day! Good job bro, this is finest prototype for our new telegram bot. I have deployed it successfully on my local machine and it works well:

`▲ ~/m/goflood-perl-bot at main ✔ sudo sh bot.sh`
`[sudo] password for mesh:` 
`▲ ~/m/goflood-perl-bot at main ✔ cat /dev/telegram`
`I work`
`I work`

I hope to see your new pull requests in the nearest future. Keep working!

**Pull request merged**
